#! /bin/sh

# Autostart for bspwm
killall -q sxhkd
sxhkd &
picom --experimental-backends &
dunst &

# Monitor setup
MONITOR1=eDP1
if xrandr -q | grep -q "^DP[0-9] connected*"; then
  $HOME/.screenlayout/dell_with_benq_pd.sh;
  MONITOR2=DP1
  bspc monitor $MONITOR2 -d 1 2 3 4 5 
  bspc config -m $MONITOR2 top_padding 20
  bspc config -m $MONITOR2 bottom_padding 20
  bspc monitor $MONITOR1 -d 1 2 3 4 5
else
  bspc monitor $MONITOR1 -d 1 2 3 4 5 6 7 8 9 10
fi
bspc config -m $MONITOR1 top_padding 20
bspc config -m $MONITOR1 bottom_padding 20

# Post Monitor setup
$HOME/.config/polybar/launch.sh &
feh --bg-scale ~/Pictures/Wallpapers/mountains.jpg

# bspwm setup
bspc config border_width         3
bspc config window_gap           20
bspc config focused_border_color "#689d6a"

bspc config split_ratio        0.52
bspc config borderless_monocle true
bspc config gapless_monocle    true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled 
bspc rule -a Emacs state=tiled 
bspc rule -a obs desktop='^8'
bspc rule -a 'VirtualBox Manager' desktop='^9'
bspc rule -a 'VirtualBox Machine' desktop='^10'

# Autostart programs
$HOME/.local/scripts/autostart.sh
