#! /bin/sh

# Autostart for bspwm
killall -q sxhkd
sxhkd &
killall -q picom
picom --experimental-backends &
killall -q dunst
dunst &

# Monitor setup
MONITOR1=DP-0
# Configuration 1
bspc monitor $MONITOR1 -d 1 2 3 4 5 6 7 8 9 10
# Configuration 2
#MONITOR2=HDMI-0
#$HOME/.screenlayout/dual_screen.sh;
#bspc monitor $MONITOR1 -d 1 2 3 4 5
#bspc monitor $MONITOR2 -d 6 7 8 9 10

# Post Monitor setup
$HOME/.config/polybar/launch.sh &
feh --bg-scale ~/Pictures/Wallpapers/gruv-4.jpg

# bspwm setup
bspc config border_width         3
bspc config window_gap           20
bspc config focused_border_color "#689d6a"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled 
bspc rule -a Emacs state=tiled 
bspc rule -a obs desktop='^8'
bspc rule -a 'VirtualBox Manager' desktop='^9'
bspc rule -a 'VirtualBox Machine' desktop='^9'
bspc rule -a Pavucontrol desktop='^10'
bspc rule -a easyeffects desktop='^10'

# Autostart programs
$HOME/.local/scripts/autostart.sh

# Execute golden-ratio plugin
#[ -f ~/Documents/GithubProjects/golden/run.sh ] &&
#  exec ~/Documents/GithubProjects/golden/run.sh &
